#!/usr/bin/env python3
"""Standalone dev-only faucet for substrate chains.

Listens on an HTTP endpoint and submits `Balances.transfer_keep_alive` from a
single funded account (typically `//Alice` on a dev chain) to whichever
destination is requested. Rate-limits per destination so a misbehaving caller
can't drain the funding key.

Designed to be deployable independently of the rest of `quip-protocol`:
copy this single file plus `substrate-interface`, `aiohttp`, `dilithium-py`,
and `blake3` and it runs. No imports from `shared/` and no other quip
modules.

**Two signing modes**:
  - **sr25519** — vanilla `MultiSignature` chains. The funder URI (default
    `//Alice`) is resolved by substrate-interface and extrinsics go through
    `create_signed_extrinsic`.
  - **hybrid** — chains that use the `HybridTxSignature` envelope
    (sr25519 + ML-DSA-44, FIPS 204 / quip-crypto-primitives). The funder URI
    is resolved against a precomputed `DEV_HYBRID_SEEDS` table because
    substrate's URI-to-master-seed path is non-trivial to replicate; we
    build the extrinsic bytes by hand because substrate-interface 1.8.1
    doesn't know about `HybridTxSignature`, `AuthorizeCall`, etc.

The mode is auto-detected by inspecting chain metadata at startup — no CLI
flag needed.

**Never run against a production chain.** The startup check refuses to bind
unless the connected chain's `System.chain` matches a known dev name. Pass
`--allow-any-chain` or set `QUIP_FAUCET_ALLOW_ANY_CHAIN=1` to override —
only do that in deliberately controlled environments.

Usage:
    python faucet_bot.py --node-url ws://localhost:9944 \\
        --faucet-key //Alice --listen 127.0.0.1 --port 8087

Funding request:
    POST /request  {"dest": "0x<32-byte hex>", "amount": <plancks>}
    (alias: POST /faucet — legacy path, same body)
    Response 200: {"extrinsic_hash": "0x...", "block_hash": "0x...",
                   "amount": N, "dest": "..."}
    Response 429: rate limited (includes retry_after_seconds)
    Response 4xx/5xx: error detail in the JSON body
"""
from __future__ import annotations

import argparse
import asyncio
import hashlib
import hmac
import logging
import os
import socket
import sys
import time
from dataclasses import dataclass
from typing import Dict, Optional, Tuple

from aiohttp import web
from dilithium_py.ml_dsa import ML_DSA_44
from scalecodec.utils.ss58 import ss58_decode, ss58_encode
from substrateinterface import Keypair, KeypairType, SubstrateInterface


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Dev chain names matched by prefix. `--chain=local3` reports
# "Local Testnet (3 Validators)" so a prefix match keeps the list short.
DEV_CHAIN_PREFIXES = (
    "Development",
    "Local Testnet",
    "quip-local",
)

# One funding per minute per destination address. Keeps a misbehaving caller
# from draining the funding key, but doesn't get in the way of legitimate
# bootstrap workflows that run a couple of times back-to-back.
DEFAULT_RATE_LIMIT_SECONDS = 60

# Default funding amount: 1000 UNIT assuming 12-decimal chains (matches
# standard Substrate dev presets). Override per request.
#
# "Planck" is the Substrate/Polkadot term for the smallest divisible balance
# unit (analogous to `wei` on Ethereum or `satoshi` on Bitcoin). 1 UNIT =
# 10^12 plancks on 12-decimal chains.
DEFAULT_AMOUNT_PLANCKS = 1_000_000_000_000_000


# Hybrid suite constants — must match `quip-crypto-primitives` byte-for-byte
# (mirrors `shared/hybrid_signer.py`; kept inline so this file stays
# standalone). Pinned by the parity tests in tests/test_hybrid_signer.py.
HYBRID_LABEL = b"hybrid-sr25519-mldsa44-v1\0"  # 26 bytes
HYBRID_VERSION = 0x01
HKDF_SALT = b"hybrid-sig"
HKDF_CLASSICAL_INFO = b"classical"
HKDF_PQ_INFO = b"pq"
MASTER_SEED_LEN = 32
ACCOUNT_ID_DOMAIN = b"quip-account-v1"

SR_PK_LEN = 32
SR_SIG_LEN = 64
ML_PK_LEN = 1312
ML_SIG_LEN = 2420
HYBRID_PK_LEN = SR_PK_LEN + ML_PK_LEN          # 1344
HYBRID_SIG_LEN = SR_SIG_LEN + ML_SIG_LEN       # 2484


# Terminal transaction-pool states returned by `author_submitAndWatchExtrinsic`
# that indicate the extrinsic will never finalize. Without enumerating all of
# them the subscription handler silently waits forever on a `usurped` /
# `retracted` / `finalityTimeout` response. Mirrors
# `shared/substrate_client._HYBRID_TERMINAL_FAILURES` byte-for-byte so the
# inline copy here doesn't drift from the canonical version.
_HYBRID_TERMINAL_FAILURES = frozenset(
    {"dropped", "invalid", "usurped", "retracted", "finalitytimeout"}
)


# Dev URI → master seed. Generated by the Rust helper
# `quip-protocol-rs/crates/transaction-crypto/examples/dump_dev_seeds.rs` —
# regenerate if the chain's dev mnemonic / derivation path changes. These
# are the *master* seeds; HKDF expands each into a (sr25519_seed, ml_dsa_seed)
# pair via `derive_component_seeds`.
DEV_HYBRID_SEEDS = {
    "//Alice": bytes.fromhex(
        "e5be9a5092b81bca64be81d212e7f2f9eba183bb7a90954f7b76361f6edb5c0a"
    ),
    "//Bob": bytes.fromhex(
        "398f0c28f98885e046333d4a41c19cee4c37368a9832c6502f6cfd182e2aef89"
    ),
    "//Alice//stash": bytes.fromhex(
        "3c881bc4d45926680c64a7f9315eeda3dd287f8d598f3653d7c107799c5422b3"
    ),
}


logger = logging.getLogger("faucet_bot")


@dataclass
class FaucetConfig:
    node_url: str
    faucet_key_uri: str = "//Alice"
    listen_host: str = "127.0.0.1"
    listen_port: int = 8087
    # Float so tests + CLI can pass sub-second values without an implicit
    # int truncation. Subtraction at the throttle site already works for
    # both int and float input.
    rate_limit_seconds: float = float(DEFAULT_RATE_LIMIT_SECONDS)
    allow_any_chain: bool = False


# ---------------------------------------------------------------------------
# Hybrid signer (inlined — see shared/hybrid_signer.py for the canonical
# version used by the rest of quip-miner). Kept minimal here: we only need
# from_master_seed, account_id_bytes, public_bytes, and sign.
# ---------------------------------------------------------------------------


def _hkdf_extract_expand(*, salt: bytes, ikm: bytes, info: bytes, length: int) -> bytes:
    """Single-block (length<=32) HKDF-SHA256 extract + expand (RFC 5869)."""
    if length > 32:
        raise ValueError("single-block HKDF only supports length<=32")
    prk = hmac.new(salt, ikm, hashlib.sha256).digest()
    t = hmac.new(prk, info + bytes([1]), hashlib.sha256).digest()
    return t[:length]


def _derive_component_seeds(master_seed: bytes) -> Tuple[bytes, bytes]:
    """Expand a 32-byte master seed into (classical_seed, pq_seed)."""
    if len(master_seed) != MASTER_SEED_LEN:
        raise ValueError(
            f"master_seed must be {MASTER_SEED_LEN} bytes, got {len(master_seed)}"
        )
    classical = _hkdf_extract_expand(
        salt=HKDF_SALT, ikm=master_seed, info=HKDF_CLASSICAL_INFO, length=MASTER_SEED_LEN
    )
    pq = _hkdf_extract_expand(
        salt=HKDF_SALT, ikm=master_seed, info=HKDF_PQ_INFO, length=MASTER_SEED_LEN
    )
    return classical, pq


def _prepare_message(msg: bytes, *, ctx: bytes = b"") -> bytes:
    """M' = version || label || len(ctx) || ctx || msg."""
    if len(ctx) > 255:
        raise ValueError(f"ctx must be at most 255 bytes, got {len(ctx)}")
    return bytes([HYBRID_VERSION]) + HYBRID_LABEL + bytes([len(ctx)]) + ctx + msg


def _derive_account_id(hybrid_public: bytes) -> bytes:
    """AccountId32 = blake2_256(b"quip-account-v1" || HybridPublic)."""
    if len(hybrid_public) != HYBRID_PK_LEN:
        raise ValueError(
            f"hybrid_public must be {HYBRID_PK_LEN} bytes, got {len(hybrid_public)}"
        )
    return hashlib.blake2b(ACCOUNT_ID_DOMAIN + hybrid_public, digest_size=32).digest()


class _HybridSigner:
    """Minimal sr25519 + ML-DSA-44 composite signer for the faucet."""

    def __init__(self, master_seed: bytes) -> None:
        if len(master_seed) != MASTER_SEED_LEN:
            raise ValueError(
                f"master_seed must be {MASTER_SEED_LEN} bytes, got {len(master_seed)}"
            )
        classical_seed, pq_seed = _derive_component_seeds(master_seed)
        self._sr = Keypair.create_from_seed(
            seed_hex=classical_seed.hex(),
            crypto_type=KeypairType.SR25519,
            ss58_format=42,
        )
        self._ml_pk, self._ml_sk = ML_DSA_44.key_derive(pq_seed)

    def public_bytes(self) -> bytes:
        return bytes(self._sr.public_key) + self._ml_pk

    def account_id_bytes(self) -> bytes:
        return _derive_account_id(self.public_bytes())

    def ss58_address(self) -> str:
        return ss58_encode(self.account_id_bytes(), ss58_format=42)

    def sign(self, payload: bytes) -> bytes:
        msg_prime = _prepare_message(payload)
        sr_sig = self._sr.sign(data=msg_prime)
        if isinstance(sr_sig, str):
            sr_sig = bytes.fromhex(sr_sig[2:] if sr_sig.startswith("0x") else sr_sig)
        sr_sig = bytes(sr_sig)
        ml_sig = ML_DSA_44.sign(self._ml_sk, msg_prime)
        if len(sr_sig) != SR_SIG_LEN or len(ml_sig) != ML_SIG_LEN:
            raise RuntimeError(
                f"component signature length mismatch: sr={len(sr_sig)} ml={len(ml_sig)}"
            )
        return sr_sig + ml_sig


# ---------------------------------------------------------------------------
# SCALE compact encoders + manual v4 extrinsic builder (hybrid path)
# ---------------------------------------------------------------------------


def _strip_0x(s: str) -> str:
    return s[2:] if s.startswith("0x") else s


def _encode_compact_u32(n: int) -> bytes:
    if n < 0:
        raise ValueError(f"compact must be non-negative, got {n}")
    if n < 0x40:
        return bytes([n << 2])
    if n < 0x4000:
        return ((n << 2) | 0b01).to_bytes(2, "little")
    if n < 0x4000_0000:
        return ((n << 2) | 0b10).to_bytes(4, "little")
    raise NotImplementedError("compact u32 big-int mode not needed here")


def _encode_compact_u128(n: int) -> bytes:
    if n < 0:
        raise ValueError(f"compact must be non-negative, got {n}")
    if n < 0x40:
        return bytes([n << 2])
    if n < 0x4000:
        return ((n << 2) | 0b01).to_bytes(2, "little")
    if n < 0x4000_0000:
        return ((n << 2) | 0b10).to_bytes(4, "little")
    raw = n.to_bytes((n.bit_length() + 7) // 8, "little")
    # SCALE compact big-int mode caps at 67 bytes: the top 6 bits of the
    # mode byte encode `n_bytes - 4`, so max n_bytes = (0xff >> 2) + 4 = 67.
    if len(raw) > 67:
        raise OverflowError(
            f"compact value needs {len(raw)} bytes, exceeds 67-byte SCALE limit"
        )
    return bytes([((len(raw) - 4) << 2) | 0b11]) + raw


def _fetch_extrinsic_dispatch_error(
    iface: SubstrateInterface, *, block_hash: str, ext_hash: str
) -> Optional[str]:
    """Return a stringified `ExtrinsicFailed` event if dispatch failed.

    `author_submitAndWatchExtrinsic` only reports "this hit a block" — the
    runtime may still emit `System.ExtrinsicFailed` for that extrinsic
    index. Mirrors `shared/substrate_client._fetch_extrinsic_dispatch_error`
    so the faucet's silent-success behaviour on chain-rejected dispatches
    can't drift back. Returns None when dispatch succeeded.
    """
    block = iface.get_block(block_hash=block_hash, include_author=False)
    if block is None:
        return None
    target_hash = _strip_0x(ext_hash).lower()
    extrinsics = block.get("extrinsics") or []
    ext_idx: Optional[int] = None
    for idx, ext in enumerate(extrinsics):
        eh = getattr(ext, "extrinsic_hash", None) or (
            ext.get("extrinsic_hash") if isinstance(ext, dict) else None
        )
        if eh and _strip_0x(str(eh)).lower() == target_hash:
            ext_idx = idx
            break
    if ext_idx is None:
        return None
    events = iface.get_events(block_hash=block_hash) or []
    for ev in events:
        v = ev.value if hasattr(ev, "value") else (ev if isinstance(ev, dict) else None)
        if not isinstance(v, dict):
            continue
        phase = v.get("phase") or {}
        if isinstance(phase, dict):
            applied = phase.get("ApplyExtrinsic")
            if applied is None or int(applied) != ext_idx:
                continue
        elif isinstance(phase, (int, str)):
            try:
                if int(phase) != ext_idx:
                    continue
            except (ValueError, TypeError):
                continue
        else:
            continue
        event = v.get("event") or v
        module_id = event.get("module_id") or event.get("pallet")
        event_id = event.get("event_id") or event.get("variant") or event.get("name")
        if module_id == "System" and event_id == "ExtrinsicFailed":
            attrs = event.get("attributes") or event.get("fields") or {}
            return f"Module(ExtrinsicFailed, attrs={attrs!r})"
    return None


def _build_hybrid_signed_extrinsic(
    *,
    iface: SubstrateInterface,
    signer: _HybridSigner,
    call_module: str,
    call_function: str,
    call_params: dict,
) -> Tuple[bytes, str]:
    """Construct a hybrid-signed v4 extrinsic byte-by-byte.

    Mirrors `shared/substrate_client._build_hybrid_signed_extrinsic`. See
    that function's docstring for the full layout reference.
    """
    call = iface.compose_call(
        call_module=call_module,
        call_function=call_function,
        call_params=call_params,
    )
    raw_call = call.data.data if hasattr(call.data, "data") else call.data
    if hasattr(raw_call, "tobytes"):
        call_bytes = bytes(raw_call)
    elif isinstance(raw_call, str):
        call_bytes = bytes.fromhex(_strip_0x(raw_call))
    else:
        call_bytes = bytes(raw_call)

    account = signer.account_id_bytes()
    nonce = iface.get_account_nonce(account_address="0x" + account.hex())
    genesis_hex = iface.get_block_hash(block_id=0)
    rv = iface.rpc_request("state_getRuntimeVersion", [])["result"]
    spec_version = int(rv["specVersion"])
    tx_version = int(rv["transactionVersion"])
    genesis_bytes = bytes.fromhex(_strip_0x(genesis_hex))

    extra = (
        b""                                  # AuthorizeCall
        + b""                                # CheckNonZeroSender
        + b""                                # CheckSpecVersion
        + b""                                # CheckTxVersion
        + b""                                # CheckGenesis
        + b"\x00"                            # CheckMortality: Era::immortal
        + _encode_compact_u32(int(nonce))    # CheckNonce
        + b""                                # CheckWeight
        + _encode_compact_u128(0)            # ChargeTransactionPayment tip=0
        + b"\x00"                            # CheckMetadataHash: Mode::Disabled
        + b""                                # WeightReclaim
    )
    additional = (
        b""                                  # AuthorizeCall
        + b""                                # CheckNonZeroSender
        + spec_version.to_bytes(4, "little") # CheckSpecVersion
        + tx_version.to_bytes(4, "little")   # CheckTxVersion
        + genesis_bytes                      # CheckGenesis
        + genesis_bytes                      # CheckMortality (immortal -> genesis)
        + b""                                # CheckNonce
        + b""                                # CheckWeight
        + b""                                # ChargeTransactionPayment
        + b"\x00"                            # CheckMetadataHash: Option::None
        + b""                                # WeightReclaim
    )

    payload = call_bytes + extra + additional
    payload_to_sign = (
        hashlib.blake2b(payload, digest_size=32).digest()
        if len(payload) > 256
        else payload
    )
    signature_bytes = signer.sign(payload_to_sign)
    hybrid_sig_scale = signer.public_bytes() + signature_bytes

    body = (
        bytes([0x84])                        # v4 | 0x80 signed flag
        + b"\x00"                            # MultiAddress::Id discriminator
        + account
        + hybrid_sig_scale
        + extra
        + call_bytes
    )
    full_extrinsic = _encode_compact_u32(len(body)) + body
    ext_hash = "0x" + hashlib.blake2b(full_extrinsic, digest_size=32).digest().hex()
    return full_extrinsic, ext_hash


def _chain_uses_hybrid_signature(iface: SubstrateInterface) -> bool:
    """Inspect runtime metadata for `HybridTxSignature` in the type table.

    Returns True if the chain's extrinsic signature type is
    `quip_transaction_crypto::HybridTxSignature`; False for vanilla
    `MultiSignature` chains. Substrate's runtime metadata is versioned
    (V14, V15, ...); the type table is reached under whatever version
    key the chain returned. Iterate over the available versions rather
    than hard-coding "V14" so a chain upgraded to V15 doesn't silently
    fall back to sr25519 mode.

    Raises `RuntimeError` if metadata can't be introspected at all —
    silently defaulting to sr25519 on a hybrid chain produces opaque
    submission failures downstream and is the worst place to fail soft.
    """
    md = iface.get_metadata()
    # md.value is a tuple `(magic_bytes, {version_key: {...}})` for V14+
    # metadata. Tolerate either shape (`(magic, table)` or a dict).
    table = md.value[1] if isinstance(md.value, (list, tuple)) else md.value
    if not isinstance(table, dict):
        raise RuntimeError(
            f"unexpected metadata shape from chain: {type(table).__name__}"
        )
    types_list = None
    for version_key, payload in table.items():
        if not isinstance(payload, dict):
            continue
        types_section = payload.get("types")
        if isinstance(types_section, dict):
            candidate = types_section.get("types")
            if isinstance(candidate, list):
                types_list = candidate
                logger.info("metadata version detected: %s", version_key)
                break
    if types_list is None:
        raise RuntimeError(
            "could not locate `types.types` in chain metadata; "
            f"keys present: {sorted(table.keys())!r}. The chain may be "
            "running an unsupported metadata version."
        )
    for t in types_list:
        path = t["type"].get("path") or []
        if "HybridTxSignature" in path:
            return True
    return False


# ---------------------------------------------------------------------------
# Faucet service
# ---------------------------------------------------------------------------


class SubstrateFaucet:
    """HTTP service that signs `Balances.transfer_keep_alive` extrinsics."""

    def __init__(self, config: FaucetConfig) -> None:
        self.config = config
        self._iface: Optional[SubstrateInterface] = None
        # One of these is populated after `start()` per the detected chain
        # mode. The vanilla `Keypair` path is what substrate-interface 1.8.1
        # expects; the `_HybridSigner` is the post-Phase 7 composite.
        self._sr_keypair: Optional[Keypair] = None
        self._hybrid_signer: Optional[_HybridSigner] = None
        self._is_hybrid = False
        self._funder_address: str = ""  # for logging / display
        self._last_funded: Dict[str, float] = {}
        self._rate_limit_lock = asyncio.Lock()
        # `SubstrateInterface` keeps a single ws connection and isn't safe
        # against concurrent calls. The faucet serializes every chain
        # interaction (compose / sign / submit) behind this lock. For a dev
        # faucet the loss of parallelism is fine, and it prevents the
        # Broken-pipe and torn-JSON failure modes that show up under load.
        self._chain_lock = asyncio.Lock()
        self._runner: Optional[web.AppRunner] = None
        self._loop: Optional[asyncio.AbstractEventLoop] = None

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    async def start(self) -> None:
        self._loop = asyncio.get_running_loop()
        self._iface = await self._run(
            lambda: SubstrateInterface(url=self.config.node_url)
        )
        await self._verify_dev_chain()
        self._is_hybrid = await self._run(
            lambda: _chain_uses_hybrid_signature(self._iface)
        )
        self._init_funder()

        app = web.Application()
        # `/request` is the canonical path shared with the standalone
        # `gitlab.com/quip.network/faucet` deployment; `/faucet` is the
        # legacy alias kept for pre-v0.2 callers and won't be removed
        # without a deprecation cycle.
        app.router.add_post("/request", self._handle_faucet)
        app.router.add_post("/faucet", self._handle_faucet)
        app.router.add_get("/health", self._handle_health)

        self._runner = web.AppRunner(app)
        await self._runner.setup()
        site = web.TCPSite(
            self._runner,
            host=self.config.listen_host,
            port=self.config.listen_port,
        )
        await site.start()
        logger.info(
            "faucet listening: http://%s:%d mode=%s funder=%s",
            self.config.listen_host,
            self.config.listen_port,
            "hybrid" if self._is_hybrid else "sr25519",
            self._funder_address,
        )

    async def stop(self) -> None:
        if self._runner is not None:
            await self._runner.cleanup()
            self._runner = None
        if self._iface is not None:
            iface = self._iface
            self._iface = None
            def _close() -> None:
                try:
                    iface.close()
                except AttributeError:
                    pass  # older substrate-interface versions
            await self._run(_close)

    def _init_funder(self) -> None:
        """Resolve the configured funder URI to the right signer type."""
        uri = self.config.faucet_key_uri
        if self._is_hybrid:
            if uri not in DEV_HYBRID_SEEDS:
                raise RuntimeError(
                    f"hybrid chain requires a known dev URI for the funder "
                    f"(got {uri!r}); known: {sorted(DEV_HYBRID_SEEDS)}. "
                    "Substrate URI derivation can't reproduce the master seed "
                    "for arbitrary URIs — generate keys with the dump_dev_seeds "
                    "Rust example and add them to DEV_HYBRID_SEEDS to extend."
                )
            self._hybrid_signer = _HybridSigner(DEV_HYBRID_SEEDS[uri])
            self._funder_address = self._hybrid_signer.ss58_address()
        else:
            self._sr_keypair = Keypair.create_from_uri(
                uri, crypto_type=KeypairType.SR25519
            )
            self._funder_address = self._sr_keypair.ss58_address

    # ------------------------------------------------------------------
    # Handlers
    # ------------------------------------------------------------------

    async def _handle_health(self, _request: web.Request) -> web.Response:
        return web.json_response({"status": "ok"})

    async def _handle_faucet(self, request: web.Request) -> web.Response:
        try:
            body = await request.json()
        except ValueError:
            return web.json_response({"error": "invalid json"}, status=400)

        dest = body.get("dest")
        if not isinstance(dest, str) or not dest:
            return web.json_response(
                {"error": "missing or invalid 'dest' (ss58 or 0x-hex AccountId)"},
                status=400,
            )

        amount = body.get("amount", DEFAULT_AMOUNT_PLANCKS)
        if not isinstance(amount, int) or amount <= 0:
            return web.json_response(
                {"error": "missing or invalid 'amount' (positive integer plancks)"},
                status=400,
            )

        # Reject malformed dest before the rate-limit table is keyed by it —
        # otherwise a caller sending garbage gets a unique rate-limit slot
        # per malformed string and trivially defeats the per-destination
        # throttle (and burns a chain RPC round-trip per attempt).
        normalized_dest = _normalize_dest(dest)
        if normalized_dest is None:
            return web.json_response(
                {"error": "invalid 'dest': not a valid SS58 address or 0x-hex AccountId"},
                status=400,
            )

        async with self._rate_limit_lock:
            now = time.monotonic()
            last = self._last_funded.get(normalized_dest, 0.0)
            wait = self.config.rate_limit_seconds - (now - last)
            if wait > 0:
                return web.json_response(
                    {
                        "error": "rate limited",
                        "retry_after_seconds": round(wait, 1),
                    },
                    status=429,
                )

        logger.info(
            "funding %s with %d plancks from %s (mode=%s)",
            normalized_dest,
            amount,
            self._funder_address,
            "hybrid" if self._is_hybrid else "sr25519",
        )
        try:
            async with self._chain_lock:
                receipt = await self._run(
                    lambda: self._submit_transfer(dest=dest, amount=amount)
                )
        except Exception:  # noqa: BLE001 — log internals, return a stable code
            # Don't burn the rate-limit slot — the transfer never happened,
            # so retries should be allowed immediately rather than locking
            # the caller out for `rate_limit_seconds`. Don't echo `str(exc)`
            # to the HTTP caller either — it leaks substrate-interface
            # internals (RemoteDisconnected paths, scale decode errors)
            # without telling the caller anything actionable. Operators
            # diagnose via the server logs.
            logger.exception(
                "faucet transfer failed: dest=%s amount=%d", dest, amount
            )
            return web.json_response(
                {"error": "transfer failed; see faucet logs"}, status=502
            )
        # Commit the rate-limit slot only after the transfer succeeded.
        async with self._rate_limit_lock:
            self._last_funded[normalized_dest] = time.monotonic()

        if isinstance(receipt, dict):
            # Hybrid path returns a plain dict (manual submission); already
            # validated for inclusion in `_submit_hybrid_transfer`.
            return web.json_response(
                {
                    "extrinsic_hash": receipt.get("extrinsic_hash", ""),
                    "block_hash": receipt.get("block_hash"),
                    "amount": amount,
                    "dest": dest,
                }
            )

        if not getattr(receipt, "is_success", True):
            return web.json_response(
                {
                    "error": str(getattr(receipt, "error_message", "unknown")),
                    "extrinsic_hash": str(getattr(receipt, "extrinsic_hash", "")),
                },
                status=502,
            )

        return web.json_response(
            {
                "extrinsic_hash": str(getattr(receipt, "extrinsic_hash", "")),
                "block_hash": str(getattr(receipt, "block_hash", "") or "") or None,
                "amount": amount,
                "dest": dest,
            }
        )

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    def _submit_transfer(self, *, dest: str, amount: int):
        # Idle websocket connections to the substrate node go stale after
        # ~minutes and the first send surfaces in several shapes depending on
        # which layer breaks: `BrokenPipeError` from os.send, `OSError` /
        # `socket.error` from socket flush, `ConnectionError` family from
        # urllib3, or `JSONDecodeError` from a truncated frame partway
        # through. Treat all transport-layer failures as "reconnect and
        # retry once" — distinguishing them is a debugging concern, not
        # something the retry policy cares about.
        # Don't include `ValueError` here even though substrate-interface
        # uses it for torn JSON: it overlaps with legitimate "bad params"
        # paths we don't want to silently retry. A broken socket will also
        # surface as one of the transport errors below on the next attempt.
        transport_errors: Tuple[type, ...] = (
            BrokenPipeError,
            ConnectionError,
            OSError,
            EOFError,
            TimeoutError,
        )
        for attempt in (1, 2):
            try:
                if self._is_hybrid:
                    return self._submit_hybrid_transfer(dest=dest, amount=amount)
                return self._submit_sr25519_transfer(dest=dest, amount=amount)
            except transport_errors as exc:
                if attempt == 2:
                    raise
                logger.warning(
                    "substrate websocket appears dead (%s: %s); "
                    "reconnecting and retrying once",
                    type(exc).__name__,
                    exc,
                )
                self._reconnect_iface()
        raise RuntimeError("unreachable: retry loop exhausted")

    def _submit_sr25519_transfer(self, *, dest: str, amount: int):
        call = self._iface.compose_call(
            call_module="Balances",
            call_function="transfer_keep_alive",
            call_params={"dest": dest, "value": amount},
        )
        extrinsic = self._iface.create_signed_extrinsic(
            call=call, keypair=self._sr_keypair
        )
        return self._iface.submit_extrinsic(
            extrinsic, wait_for_inclusion=True
        )

    def _submit_hybrid_transfer(self, *, dest: str, amount: int) -> dict:
        """Build + submit a hybrid-signed transfer, wait for in-block.

        Returns a dict with `extrinsic_hash`, `block_hash`, and (on
        dispatch failure) `error`. Raises `RuntimeError` for any
        terminal pool status (`dropped` / `invalid` / `usurped` /
        `retracted` / `finalityTimeout`) so the HTTP caller gets a
        useful 502 instead of a silent hang.
        """
        ext_bytes, ext_hash = _build_hybrid_signed_extrinsic(
            iface=self._iface,
            signer=self._hybrid_signer,
            call_module="Balances",
            call_function="transfer_keep_alive",
            call_params={"dest": dest, "value": amount},
        )
        ext_hex = "0x" + ext_bytes.hex()

        def _result_handler(message, update_nr, subscription_id):  # noqa: ARG001
            params = message.get("params") or {}
            res = params.get("result")
            if isinstance(res, dict):
                lower = {k.lower(): v for k, v in res.items()}
                if "inblock" in lower:
                    self._iface.rpc_request(
                        "author_unwatchExtrinsic", [subscription_id]
                    )
                    return {
                        "extrinsic_hash": ext_hash,
                        "block_hash": lower["inblock"],
                    }
                if "finalized" in lower:
                    self._iface.rpc_request(
                        "author_unwatchExtrinsic", [subscription_id]
                    )
                    return {
                        "extrinsic_hash": ext_hash,
                        "block_hash": lower["finalized"],
                    }
            elif isinstance(res, str) and res.lower() in _HYBRID_TERMINAL_FAILURES:
                self._iface.rpc_request(
                    "author_unwatchExtrinsic", [subscription_id]
                )
                raise RuntimeError(f"hybrid extrinsic rejected: {res}")
            return None  # non-terminal status — keep waiting

        response = self._iface.rpc_request(
            "author_submitAndWatchExtrinsic",
            [ext_hex],
            result_handler=_result_handler,
        )
        # `rpc_request` returns whatever `_result_handler` returned. A None
        # response means the subscription closed before any terminal status
        # fired — without raising, the caller sees `block_hash=None` and
        # treats it as success. Fail fast instead.
        if not isinstance(response, dict) or not response.get("block_hash"):
            raise RuntimeError(
                "hybrid extrinsic subscription closed before inclusion "
                f"(ext_hash={ext_hash})"
            )
        block_hash = response["block_hash"]
        # author_submitAndWatchExtrinsic only reports inclusion — a
        # `System.ExtrinsicFailed` event in the same block still means the
        # chain rejected the dispatch. Fetch events at the block hash and
        # surface any matching failure.
        error = _fetch_extrinsic_dispatch_error(
            self._iface, block_hash=block_hash, ext_hash=ext_hash
        )
        if error:
            raise RuntimeError(f"hybrid extrinsic dispatch failed: {error}")
        return {"extrinsic_hash": ext_hash, "block_hash": block_hash}

    def _reconnect_iface(self) -> None:
        old = self._iface
        if old is not None:
            try:
                old.close()
            except Exception:  # noqa: BLE001 — best-effort tear-down
                pass
        self._iface = SubstrateInterface(url=self.config.node_url)

    async def _verify_dev_chain(self) -> None:
        if self.config.allow_any_chain or os.environ.get(
            "QUIP_FAUCET_ALLOW_ANY_CHAIN"
        ) == "1":
            logger.warning(
                "faucet running against non-dev chain because allow_any_chain=true; "
                "this is unsafe outside controlled environments"
            )
            return

        chain_name = await self._run(lambda: self._iface.chain)
        if not any(chain_name.startswith(p) for p in DEV_CHAIN_PREFIXES):
            raise RuntimeError(
                f"refusing to run faucet against chain {chain_name!r}; pass "
                "--allow-any-chain only if you really mean to fund accounts "
                "on a non-dev chain"
            )
        logger.info("faucet verified dev chain: %s", chain_name)

    async def _run(self, fn):
        loop = self._loop or asyncio.get_running_loop()
        return await loop.run_in_executor(None, fn)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _normalize_dest(dest: str) -> Optional[str]:
    """Canonicalize dest as 0x-prefixed lowercase hex for rate-limit keys.

    Accepts both `0x...` hex and SS58-encoded addresses; both decode to the
    same 32-byte AccountId, so they share one rate-limit slot. Without SS58
    canonicalization a caller could alternate representations to bypass the
    per-destination throttle.

    Returns `None` for malformed inputs so callers can reject the request
    before keying the rate-limit table on garbage. The previous behaviour
    (pass-through on failure) gave every distinct malformed string its own
    rate-limit slot — trivial throttle bypass.
    """
    if dest.startswith("0x") or dest.startswith("0X"):
        hex_body = dest[2:]
        # 32-byte AccountId32 = 64 hex chars. Reject anything off-shape.
        if len(hex_body) != 64:
            return None
        try:
            bytes.fromhex(hex_body)
        except ValueError:
            return None
        return "0x" + hex_body.lower()
    try:
        pubkey_hex = ss58_decode(dest)
    except (ValueError, IndexError, TypeError):
        # Malformed SS58 raises one of these depending on the failure mode.
        return None
    return "0x" + pubkey_hex.lower()


def _is_port_free(host: str, port: int) -> bool:
    try:
        with socket.socket() as s:
            s.bind((host, port))
            return True
    except OSError:
        return False


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="faucet_bot",
        description="Standalone dev faucet for substrate chains.",
    )
    parser.add_argument(
        "--node-url",
        required=True,
        help="Substrate node WebSocket URL (e.g. ws://localhost:9944)",
    )
    parser.add_argument(
        "--faucet-key",
        default="//Alice",
        help="Substrate URI for the funded sender account (default: //Alice). "
        "On hybrid chains must be one of //Alice, //Bob, //Alice//stash.",
    )
    parser.add_argument(
        "--listen",
        default="127.0.0.1",
        help="Bind address (default: 127.0.0.1)",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=8087,
        help="Bind port (default: 8087)",
    )
    parser.add_argument(
        "--rate-limit-seconds",
        type=float,
        default=float(DEFAULT_RATE_LIMIT_SECONDS),
        help="Seconds between requests per destination address",
    )
    parser.add_argument(
        "--allow-any-chain",
        action="store_true",
        help="Allow running against non-dev chains. UNSAFE.",
    )
    parser.add_argument(
        "--log-level",
        default="INFO",
        choices=("DEBUG", "INFO", "WARNING", "ERROR"),
        help="Log verbosity (default: INFO)",
    )
    return parser


def _setup_logging(level: str) -> None:
    logging.basicConfig(
        level=level,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
        stream=sys.stderr,
    )


async def _run(config: FaucetConfig) -> None:
    faucet = SubstrateFaucet(config)
    await faucet.start()
    try:
        # Block forever; aiohttp's TCPSite has already bound the port and
        # the runner serves requests in the background.
        await asyncio.Event().wait()
    finally:
        await faucet.stop()


def main(argv: Optional[list] = None) -> int:
    args = _build_parser().parse_args(argv)
    _setup_logging(args.log_level)

    if not _is_port_free(args.listen, args.port):
        logger.error(
            "port %s:%d already in use; pick a different --port",
            args.listen,
            args.port,
        )
        return 2

    config = FaucetConfig(
        node_url=args.node_url,
        faucet_key_uri=args.faucet_key,
        listen_host=args.listen,
        listen_port=args.port,
        rate_limit_seconds=args.rate_limit_seconds,
        allow_any_chain=args.allow_any_chain,
    )
    try:
        asyncio.run(_run(config))
    except KeyboardInterrupt:
        logger.info("faucet stopped")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
