"""Cross-language parity test for `shared.quantum_proof_of_work.derive_nonce`.

Loads the shared fixture maintained alongside the Rust pallet at
``crates/quantum-validation/tests/fixtures/python_parity.json`` in the
``quip-protocol-rs`` sibling checkout. Fixture schema:

  - ``last_winning_hash_hex`` : 32-byte hex (``block_hash(LastProofBlock)``)
  - ``miner_hex``        : 32-byte hex (the canonical miner identity is
                           ``blake2_256(SCALE(account_id))``; tests pin
                           specific 32-byte buffers directly)
  - ``salt_hex``         : 32-byte hex
  - ``expected_nonce_hex``: 32-byte hex (full BLAKE3 digest)

The fixture file is regenerated by ``tests/generate_parity_vectors.py``.
The test is skipped if the fixture file cannot be located so that
contributors without the Rust repo checked out alongside this one can
still run the rest of the suite.
"""
from __future__ import annotations

import json
import os
from pathlib import Path

import pytest

from shared.quantum_proof_of_work import derive_nonce


def _fixture_path() -> Path | None:
    """Search a few well-known locations for the parity fixture.

    Set ``QUIP_RUST_FIXTURE_DIR`` to point at the directory containing
    ``python_parity.json``. If the env var is set but the file isn't there,
    we ``pytest.fail`` — silently ignoring an explicit override would let a
    misconfigured CI mask a real parity break.
    """
    env_override = os.environ.get("QUIP_RUST_FIXTURE_DIR")
    if env_override:
        override_path = Path(env_override) / "python_parity.json"
        if not override_path.exists():
            pytest.fail(
                f"QUIP_RUST_FIXTURE_DIR={env_override!r} does not contain "
                "python_parity.json"
            )
        return override_path

    sibling = (
        Path(__file__).parent.parent.parent
        / "quip-protocol-rs"
        / "crates"
        / "quantum-validation"
        / "tests"
        / "fixtures"
        / "python_parity.json"
    )
    return sibling if sibling.exists() else None


_FIXTURE_PATH = _fixture_path()
_SKIP_REASON = (
    "Rust parity fixture not found. Check out quip-protocol-rs alongside "
    "this repo or set QUIP_RUST_FIXTURE_DIR=/path/to/fixtures."
)


def _load_cases(key: str):
    if _FIXTURE_PATH is None:
        return [
            pytest.param(
                None,
                id="fixture-missing",
                marks=pytest.mark.skip(reason=_SKIP_REASON),
            )
        ]
    fixture = json.loads(_FIXTURE_PATH.read_text())
    cases = fixture.get(key, [])
    if not cases:
        return [
            pytest.param(
                None,
                id=f"{key}-missing-from-fixture",
                marks=pytest.mark.skip(
                    reason=f"fixture has no {key!r} cases yet; "
                    "regenerate with tests/generate_parity_vectors.py"
                ),
            )
        ]
    return [pytest.param(case, id=case["name"]) for case in cases]


@pytest.mark.parametrize("case", _load_cases("derive_nonce_cases"))
def test_derive_nonce_matches_rust(case):
    actual = derive_nonce(
        last_winning_hash=bytes.fromhex(case["last_winning_hash_hex"]),
        miner=bytes.fromhex(case["miner_hex"]),
        salt=bytes.fromhex(case["salt_hex"]),
    )
    assert actual.hex() == case["expected_nonce_hex"]


def test_derive_nonce_accepts_zero_seed():
    out = derive_nonce(b"\x00" * 32, b"\x00" * 32, b"\x00" * 32)
    assert isinstance(out, bytes)
    assert len(out) == 32
