#!/bin/bash
# Entrypoint for the quip-miner Docker image (CPU / CUDA).
#
# The container is a stateless substrate-attached miner: no chain
# state, no P2P, no genesis block. On startup we just need a keystore
# and one or more validator URLs. Everything else flows through
# `quip-miner $MODE --config /data/config.toml` with CLI flags from
# env vars overriding the TOML defaults.
#
# Persistent state under /data:
#   config.toml      — copied from /app/quip-miner.docker.toml on first
#                      run; operators can edit it directly afterwards.
#   keystore.json    — auto-generated by `quip-miner keygen` on first
#                      run. Hybrid sr25519 + ML-DSA-44, plaintext seed.
#                      BACK THIS UP — the chain key lives here.
set -euo pipefail

echo "========================================"
echo "Quip Miner (substrate)"
echo "========================================"
echo "Start time: $(date)"

CONFIG_FILE="/data/config.toml"
TEMPLATE_FILE="/app/quip-miner.docker.toml"
KEYSTORE_FILE="${QUIP_SIGNER_KEY:-/data/keystore.json}"
# Image baseline (CPU image sets QUIP_MODE=cpu, CUDA image sets =gpu);
# operators can still override on `docker run -e QUIP_MODE=...`.
MODE="${QUIP_MODE:-cpu}"
# pow | mempool | both — passed to `quip-miner $MODE --mode`.
MINE_MODE="${QUIP_MINE_MODE:-pow}"

case "$MODE" in
    cpu|gpu|qpu) ;;
    *)
        echo "ERROR: QUIP_MODE='$MODE' is invalid. Expected cpu, gpu, or qpu." >&2
        exit 2
        ;;
esac

# ── Privilege-drop setup ─────────────────────────────────────────
# Container starts as root so we can chown /data and generate the
# keystore with the right ownership. We drop to `quip` before exec.
# PUID/PGID let operators match the in-container user to their host
# UID/GID without rebuilding (default 1000:1000, PUID=0 keeps root).
PUID="${PUID:-1000}"
PGID="${PGID:-1000}"
DROP_USER=""

handle_privilege_drop() {
    if [ "$PUID" = "0" ]; then
        echo "Privilege drop: PUID=0 — running as root (legacy mode)"
        DROP_USER=""
        return
    fi

    # Align the baked-in `quip` user/group to PUID/PGID if they differ.
    local cur_uid cur_gid
    cur_uid=$(id -u quip)
    cur_gid=$(id -g quip)
    [ "$cur_gid" != "$PGID" ] && groupmod -g "$PGID" quip
    [ "$cur_uid" != "$PUID" ] && usermod  -u "$PUID" -g "$PGID" quip

    echo "Privilege drop: chown -R quip:quip /data"
    chown -R quip:quip /data

    # Re-tighten keystore after the ownership flip.
    [ -f "$KEYSTORE_FILE" ] && chmod 600 "$KEYSTORE_FILE"

    DROP_USER="quip:quip"
    echo "Privilege drop: will exec as uid=$PUID gid=$PGID"
}

# ── First run: seed config from template ──────────────────────────
mkdir -p /data
if [ ! -f "$CONFIG_FILE" ]; then
    echo "First run: seeding $CONFIG_FILE from $TEMPLATE_FILE"
    cp "$TEMPLATE_FILE" "$CONFIG_FILE"
else
    echo "Using existing config at $CONFIG_FILE"
fi

# ── First run: generate signing keystore ──────────────────────────
# Auto-keygen on first start so a bare `docker run` produces a working
# miner. Operators who want a managed key should mount their own
# keystore at $QUIP_SIGNER_KEY and the entrypoint will skip keygen.
if [ ! -f "$KEYSTORE_FILE" ]; then
    echo "First run: generating hybrid keystore at $KEYSTORE_FILE"
    quip-miner keygen --out "$KEYSTORE_FILE"
    # quip-miner keygen sets mode 0600 internally; re-assert for clarity.
    chmod 600 "$KEYSTORE_FILE"
else
    echo "Using existing keystore at $KEYSTORE_FILE"
fi

# ── Build CLI args from env vars ─────────────────────────────────
# Precedence: ENV > TOML > defaults. ENV overrides land as CLI flags
# that the quip-miner CLI already prefers over TOML values.
CLI_ARGS=(--config "$CONFIG_FILE" --signer-key "$KEYSTORE_FILE" --mode "$MINE_MODE")

# QUIP_VALIDATORS="ws://a,ws://b" → --validator ws://a --validator ws://b
if [ -n "${QUIP_VALIDATORS:-}" ]; then
    IFS=',' read -ra _VALIDATORS <<< "$QUIP_VALIDATORS"
    for url in "${_VALIDATORS[@]}"; do
        url="$(echo "$url" | xargs)"
        [ -n "$url" ] && CLI_ARGS+=(--validator "$url")
    done
fi

if [ -n "${QUIP_FAUCET_URL:-}" ]; then
    CLI_ARGS+=(--faucet-url "$QUIP_FAUCET_URL")
fi

if [ -n "${QUIP_REST_PORT:-}" ]; then
    CLI_ARGS+=(--rest-port "$QUIP_REST_PORT")
fi

if [ -n "${QUIP_REST_HOST:-}" ]; then
    CLI_ARGS+=(--rest-host "$QUIP_REST_HOST")
fi

# ── Hardware probe (GPU only — informational) ────────────────────
if [ "$MODE" = "gpu" ] && command -v nvidia-smi >/dev/null 2>&1; then
    echo "----------------------------------------"
    nvidia-smi --query-gpu=gpu_name,compute_cap --format=csv,noheader || true
    echo "----------------------------------------"
fi

# ── Launch ───────────────────────────────────────────────────────
echo "========================================"
echo "Starting quip-miner $MODE..."
echo "========================================"

handle_privilege_drop

CMD=(quip-miner "$MODE" "${CLI_ARGS[@]}")
echo "Command: ${CMD[*]}"
echo "----------------------------------------"

if [ -n "$DROP_USER" ]; then
    exec gosu "$DROP_USER" "${CMD[@]}"
else
    exec "${CMD[@]}"
fi
