#!/bin/bash
# Entrypoint for the quip-miner Docker image (CPU / CUDA).
#
# The container is a stateless substrate-attached miner: no chain
# state, no P2P, no genesis block. On startup we just need a keystore
# and one or more validator URLs. Everything else flows through
# `quip-miner $MODE --config /data/config.toml` with CLI flags from
# env vars overriding the TOML defaults.
#
# Mode resolution is config-driven via `quip-miner resolve-modes`:
# config.toml's [cpu]/[gpu]/[cuda.N]/[metal]/[modal]/[qpu]/[dwave]/
# [ibm]/[braket]/[pasqal]/[ionq]/[origin] sections pick which
# subcommand(s) run. One process per active group — the entrypoint
# spawns each as a separate `quip-miner <mode>` child and supervises
# them. QUIP_IMAGE_SUPPORTS rejects modes the image doesn't have
# libraries for. QUIP_DEFAULT_MODE is the fallback when config has
# zero backend sections.
#
# Persistent state under /data:
#   config.toml      — copied from /app/quip-miner.docker.toml on first
#                      run; operators can edit it directly afterwards.
#   keystore.json    — auto-generated by `quip-miner keygen` on first
#                      run. Hybrid sr25519 + ML-DSA-44, plaintext seed.
#                      BACK THIS UP — the chain key lives here.
set -euo pipefail

echo "========================================"
echo "Quip Miner (substrate)"
echo "========================================"
echo "Start time: $(date)"

CONFIG_FILE="/data/config.toml"
TEMPLATE_FILE="/app/quip-miner.docker.toml"
KEYSTORE_FILE="${QUIP_SIGNER_KEY:-/data/keystore.json}"
# pow | mempool | both — passed to `quip-miner $MODE --mode`.
MINE_MODE="${QUIP_MINE_MODE:-pow}"

# ── Privilege-drop setup ─────────────────────────────────────────
# Container starts as root so we can chown /data and generate the
# keystore with the right ownership. We drop to `quip` before exec.
# PUID/PGID let operators match the in-container user to their host
# UID/GID without rebuilding (default 1000:1000, PUID=0 keeps root).
PUID="${PUID:-1000}"
PGID="${PGID:-1000}"
DROP_USER=""

handle_privilege_drop() {
    if [ "$PUID" = "0" ]; then
        echo "Privilege drop: PUID=0 — running as root (legacy mode)"
        DROP_USER=""
        return
    fi

    # Align the baked-in `quip` user/group to PUID/PGID if they differ.
    local cur_uid cur_gid
    cur_uid=$(id -u quip)
    cur_gid=$(id -g quip)
    [ "$cur_gid" != "$PGID" ] && groupmod -g "$PGID" quip
    [ "$cur_uid" != "$PUID" ] && usermod  -u "$PUID" -g "$PGID" quip

    echo "Privilege drop: chown -R quip:quip /data"
    chown -R quip:quip /data

    # Re-tighten keystore after the ownership flip.
    [ -f "$KEYSTORE_FILE" ] && chmod 600 "$KEYSTORE_FILE"

    DROP_USER="quip:quip"
    echo "Privilege drop: will exec as uid=$PUID gid=$PGID"
}

# ── First run: seed config from template ──────────────────────────
mkdir -p /data
if [ ! -f "$CONFIG_FILE" ]; then
    echo "First run: seeding $CONFIG_FILE from $TEMPLATE_FILE"
    cp "$TEMPLATE_FILE" "$CONFIG_FILE"
else
    echo "Using existing config at $CONFIG_FILE"
fi

# ── First run: generate signing keystore ──────────────────────────
# Auto-keygen on first start so a bare `docker run` produces a working
# miner. Operators who want a managed key should mount their own
# keystore at $QUIP_SIGNER_KEY and the entrypoint will skip keygen.
if [ ! -f "$KEYSTORE_FILE" ]; then
    echo "First run: generating hybrid keystore at $KEYSTORE_FILE"
    quip-miner keygen --out "$KEYSTORE_FILE"
    # quip-miner keygen sets mode 0600 internally; re-assert for clarity.
    chmod 600 "$KEYSTORE_FILE"
else
    echo "Using existing keystore at $KEYSTORE_FILE"
fi

# ── Resolve subcommand(s) from config ────────────────────────────
# Defer to `quip-miner resolve-modes` so the bash glue doesn't have to
# parse TOML. The Python side is the single source of truth on which
# section names belong to which group. Returns one mode per line.
RESOLVE_ARGS=(resolve-modes --config "$CONFIG_FILE")
if [ -n "${QUIP_DEFAULT_MODE:-}" ]; then
    RESOLVE_ARGS+=(--default "$QUIP_DEFAULT_MODE")
fi
if [ -n "${QUIP_IMAGE_SUPPORTS:-}" ]; then
    RESOLVE_ARGS+=(--image-supports "$QUIP_IMAGE_SUPPORTS")
fi

# `set -e` would mask an error from the assigning subshell; capture
# both streams and inspect exit code explicitly.
if ! MODES_RAW="$(quip-miner "${RESOLVE_ARGS[@]}" 2>&1)"; then
    echo "ERROR: mode resolution failed:" >&2
    echo "$MODES_RAW" >&2
    exit 3
fi
mapfile -t MODES <<< "$MODES_RAW"
echo "Resolved ${#MODES[@]} mode(s) from config: ${MODES[*]}"

# ── Build CLI args common to every child ─────────────────────────
# Precedence: ENV > TOML > defaults. ENV overrides land as CLI flags
# that the quip-miner CLI already prefers over TOML values. Per-child
# overrides (telemetry port) are appended after these.
COMMON_ARGS=(--config "$CONFIG_FILE" --signer-key "$KEYSTORE_FILE" --mode "$MINE_MODE")

# QUIP_VALIDATORS="ws://a,ws://b" → --validator ws://a --validator ws://b
if [ -n "${QUIP_VALIDATORS:-}" ]; then
    IFS=',' read -ra _VALIDATORS <<< "$QUIP_VALIDATORS"
    for url in "${_VALIDATORS[@]}"; do
        url="$(echo "$url" | xargs)"
        [ -n "$url" ] && COMMON_ARGS+=(--validator "$url")
    done
fi

if [ -n "${QUIP_FAUCET_URL:-}" ]; then
    COMMON_ARGS+=(--faucet-url "$QUIP_FAUCET_URL")
fi

if [ -n "${QUIP_REST_HOST:-}" ]; then
    COMMON_ARGS+=(--rest-host "$QUIP_REST_HOST")
fi

# Telemetry port: each child binds a distinct port allocated from a
# base (default 8086). Operators can pin the base via QUIP_REST_PORT;
# children get base, base+1, base+2 in resolved-mode order.
REST_PORT_BASE="${QUIP_REST_PORT:-8086}"

# ── Hardware probe (GPU only — informational) ────────────────────
if [[ " ${MODES[*]} " == *" gpu "* ]] && command -v nvidia-smi >/dev/null 2>&1; then
    echo "----------------------------------------"
    nvidia-smi --query-gpu=gpu_name,compute_cap --format=csv,noheader || true
    echo "----------------------------------------"
fi

handle_privilege_drop

# ── Multi-process supervisor ─────────────────────────────────────
# One `quip-miner <mode>` process per resolved mode. The supervisor
# forwards SIGTERM/SIGINT to all children, and if any child dies
# (clean or otherwise) the whole container exits — operators or
# orchestrators (compose/k8s) re-spawn from there. Single-mode
# operation is just the N=1 case; no special path.
declare -a CHILD_PIDS=()

shutdown_children() {
    local sig="${1:-TERM}"
    for pid in "${CHILD_PIDS[@]}"; do
        if kill -0 "$pid" 2>/dev/null; then
            kill "-$sig" "$pid" 2>/dev/null || true
        fi
    done
}

# Trap once; signal handler is idempotent.
trap 'shutdown_children TERM' TERM INT

echo "========================================"
for i in "${!MODES[@]}"; do
    mode="${MODES[$i]}"
    port=$((REST_PORT_BASE + i))
    CMD=(quip-miner "$mode" "${COMMON_ARGS[@]}" --rest-port "$port")
    echo "Starting [$((i + 1))/${#MODES[@]}]: ${CMD[*]}"
    if [ -n "$DROP_USER" ]; then
        gosu "$DROP_USER" "${CMD[@]}" &
    else
        "${CMD[@]}" &
    fi
    CHILD_PIDS+=($!)
done
echo "========================================"
echo "Supervisor: ${#CHILD_PIDS[@]} child(ren) running, pids=${CHILD_PIDS[*]}"

# Wait for any child to exit. `wait -n` returns the exit code of the
# first completed child; we then tear down the rest and propagate.
EXIT_CODE=0
if wait -n "${CHILD_PIDS[@]}"; then
    EXIT_CODE=0
else
    EXIT_CODE=$?
fi
echo "Supervisor: a child exited with code $EXIT_CODE; tearing down siblings"
shutdown_children TERM

# Drain remaining children. `wait` without args waits for all
# outstanding background jobs.
wait || true
exit "$EXIT_CODE"
