[workspace]
resolver = "2"
members = [
    "quip-proto",
    "quip-protocol",
    "quip-mock-miner",
    "quip-mock-coordinator",
    "quip-coordinator",
    "quip-miner-core",
    "quip-miner-metal",
    "quip-miner-cpu",
    "quip-miner-cuda",
]

[workspace.dependencies]
tonic = "0.12"
prost = "0.13"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "time", "signal", "io-util", "sync"] }
tonic-build = "0.12"
