#!/usr/bin/env python3
"""CUDA kernel region profiling via clock64() instrumentation.

Runs SA or Gibbs kernel with auto-generated profiling enabled,
reads back per-region cycle counters, and outputs a hierarchical
breakdown showing where GPU time is spent inside the kernel.

Region names, source mappings, and hierarchy are loaded from
a JSON manifest generated by cuda_auto_profiler.py — nothing
is hardcoded.

Usage:
    python tools/cuda_profile_regions.py [--kernel gibbs|sa] \
        [--sweeps N] [--reads N] [--plot] [--flame] \
        [--flame-html]
"""

import argparse
import colorsys
import hashlib
import json
import math
import os
import re
from pathlib import Path

import cupy as cp
import numpy as np


# Color by region type
TYPE_COLORS = {
    "loop": "#2ecc71",
    "sync": "#3498db",
    "ldg": "#e67e22",
    "call": "#e74c3c",
}

# Project root for resolving .cu file paths
_PROJECT_ROOT = Path(__file__).resolve().parent.parent


# ── Manifest loading ───────────────────────────────────


def _load_manifest(kernel_name):
    """Load profiling manifest for a kernel.

    Args:
        kernel_name: 'gibbs' or 'sa'.

    Returns:
        Manifest dict with kernel, source_file,
        num_regions, profiling_mode, regions.
    """
    cu_stem = f"cuda_{kernel_name}"
    manifest_path = (
        _PROJECT_ROOT / "GPU"
        / f"{cu_stem}_profile_manifest.json"
    )
    assert manifest_path.exists(), (
        f"Manifest not found: {manifest_path}. "
        f"Run profiling first to generate it."
    )
    return json.loads(
        manifest_path.read_text(encoding="utf-8")
    )


def _source_map_from_manifest(manifest):
    """Build source_map dict from manifest regions.

    Returns dict mapping region_id -> (line_start, line_end).
    """
    source_map = {}
    for r in manifest["regions"]:
        source_map[r["id"]] = (
            r["line_start"], r["line_end"],
        )
    return source_map


def _region_names_from_manifest(manifest):
    """Build region name list indexed by ID."""
    max_id = max(r["id"] for r in manifest["regions"])
    names = [""] * (max_id + 1)
    for r in manifest["regions"]:
        names[r["id"]] = r["label"]
    return names


# ── Tree building from manifest ────────────────────────


def _build_tree_from_manifest(manifest, avg):
    """Build flamegraph tree from manifest parent_id hierarchy.

    Args:
        manifest: Profiling manifest dict.
        avg: Array of average cycle counts per region.

    Returns:
        Tree dict with name, cycles, color, children.
    """
    nodes = {}
    for r in manifest["regions"]:
        rid = r["id"]
        nodes[rid] = {
            "name": r["label"],
            "cycles": float(avg[rid]) if rid < len(avg) else 0,
            "color": TYPE_COLORS.get(r["type"], "#888"),
            "children": [],
            "parent_id": r["parent_id"],
            "source_lines": [r["line_start"], r["line_end"]],
        }

    roots = []
    for rid, node in nodes.items():
        pid = node.pop("parent_id")
        if pid is None:
            roots.append(node)
        elif pid in nodes:
            nodes[pid]["children"].append(node)
        else:
            roots.append(node)

    total = sum(n["cycles"] for n in roots)
    return {
        "name": "KERNEL_TOTAL",
        "cycles": total,
        "color": "#9b59b6",
        "children": roots,
    }


# ── GPU info ───────────────────────────────────────────


def get_gpu_info():
    """Query GPU name and SM clock rate."""
    dev = cp.cuda.Device()
    attrs = dev.attributes
    clock_khz = attrs['ClockRate']
    clock_mhz = clock_khz / 1000.0
    name = cp.cuda.runtime.getDeviceProperties(dev.id)['name']
    if isinstance(name, bytes):
        name = name.decode()
    return name, clock_khz, clock_mhz


def cycles_to_time(cycles, clock_khz):
    """Convert cycles to seconds."""
    return cycles / (clock_khz * 1000.0)


def fmt_time(seconds):
    """Format seconds as human-readable time."""
    if seconds >= 1.0:
        return f"{seconds:.2f} s"
    if seconds >= 0.001:
        return f"{seconds * 1000:.2f} ms"
    return f"{seconds * 1e6:.2f} us"


def fmt_cycles(cycles):
    """Format cycle count with commas."""
    return f"{int(cycles):,}"


# ── Problem generation ─────────────────────────────────


def build_ising_problem():
    """Build a standard Advantage topology Ising problem."""
    from dwave_topologies import DEFAULT_TOPOLOGY
    from shared.quantum_proof_of_work import (
        generate_ising_model_from_nonce,
    )

    nodes = sorted(DEFAULT_TOPOLOGY.graph.nodes())
    edges = list(DEFAULT_TOPOLOGY.graph.edges())
    h, J = generate_ising_model_from_nonce(
        42, nodes, edges, h_values=[-1, 0, 1],
    )
    return h, J


# ── Profiling runners ──────────────────────────────────


def profile_gibbs(num_reads, num_sweeps):
    """Run Gibbs kernel with profiling and return data."""
    from GPU.cuda_gibbs_sa import CudaGibbsSampler

    h, J = build_ising_problem()
    sampler = CudaGibbsSampler(profile=True)
    sampler.sample_ising(
        [h], [J],
        num_reads=num_reads,
        num_sweeps=num_sweeps,
    )
    return sampler.get_profile_data()


def profile_sa(num_reads, num_sweeps):
    """Run SA kernel with profiling and return data."""
    from GPU.cuda_sa import CudaSASampler

    h_dict, J_dict = build_ising_problem()

    sampler = CudaSASampler(profile=True)
    sampler.sample_ising(
        [h_dict], [J_dict],
        num_reads=min(num_reads, 256),
        num_sweeps=num_sweeps,
    )
    return sampler.get_profile_data()


# ── Text profile printing ─────────────────────────────


def print_profile(data, clock_khz, manifest,
                  num_reads, num_sweeps):
    """Print generic profile breakdown from manifest."""
    active = data[data.any(axis=1)]
    if len(active) == 0:
        print("No active work units found in profile data.")
        return

    n_active = len(active)
    avg = active.mean(axis=0)
    std = active.std(axis=0)
    mn = active.min(axis=0)
    mx = active.max(axis=0)

    total = sum(
        avg[r["id"]]
        for r in manifest["regions"]
        if r["parent_id"] is None
    )

    kernel_name = manifest["kernel"]
    print(f"\n{'=' * 60}")
    print(f"{kernel_name} Profile ({n_active} work units)")
    print(f"{'=' * 60}")

    # Sort regions by ID for display
    regions_sorted = sorted(
        manifest["regions"], key=lambda r: r["id"],
    )

    print(f"\n{'Region':<50} {'Avg Cycles':>14} "
          f"{'Avg Time':>10} {'%':>7}")
    print("-" * 85)
    for r in regions_sorted:
        rid = r["id"]
        if rid >= len(avg):
            continue
        indent = "  " * r["depth"]
        name = f"{indent}{r['label']}"
        c = avg[rid]
        t = cycles_to_time(c, clock_khz)
        pct = (c / total * 100) if total > 0 else 0
        print(f"{name:<50} {fmt_cycles(c):>14} "
              f"{fmt_time(t):>10} {pct:>6.1f}%")

    # Load imbalance on root regions
    root_ids = [
        r["id"] for r in manifest["regions"]
        if r["parent_id"] is None
    ]
    if root_ids:
        main_id = root_ids[0]
        print(f"\n{'Load Imbalance (region 0)':}")
        print(f"  Min: {fmt_cycles(mn[main_id]):>14}  "
              f"({fmt_time(cycles_to_time(mn[main_id], clock_khz))})")
        print(f"  Max: {fmt_cycles(mx[main_id]):>14}  "
              f"({fmt_time(cycles_to_time(mx[main_id], clock_khz))})")
        print(f"  Std: {fmt_cycles(std[main_id]):>14}  "
              f"({fmt_time(cycles_to_time(std[main_id], clock_khz))})")
        if avg[main_id] > 0:
            cv = std[main_id] / avg[main_id] * 100
            print(f"  CV:  {cv:.1f}%")


# ── Topology stats ─────────────────────────────────────


def get_topology_stats():
    """Query topology for node/edge/degree stats."""
    from dwave_topologies import DEFAULT_TOPOLOGY

    graph = DEFAULT_TOPOLOGY.graph
    num_nodes = graph.number_of_nodes()
    num_edges = graph.number_of_edges()
    avg_degree = 2.0 * num_edges / num_nodes
    num_colors = 4
    nodes_per_color = math.ceil(num_nodes / num_colors)
    return (num_nodes, num_edges, avg_degree,
            nodes_per_color, num_colors)


# ── Matplotlib flamegraph (legacy) ─────────────────────


def generate_flamegraph(data, clock_khz, kernel_name,
                        manifest, output_path):
    """Generate flamegraph SVG from profiling data."""
    try:
        import matplotlib
        matplotlib.use('Agg')
        import matplotlib.pyplot as plt
        from matplotlib.patches import Rectangle
    except ImportError:
        print("matplotlib not available, skipping flamegraph.")
        return

    active = data[data.any(axis=1)]
    if len(active) == 0:
        print("No active data for flamegraph.")
        return

    avg = active.mean(axis=0)
    tree = _build_tree_from_manifest(manifest, avg)
    total = tree["cycles"]
    if total <= 0:
        return

    rows = _layout_tree(tree, 0, 0.0, 1.0, total)

    num_rows = max(r[1] for r in rows) + 1
    fig_height = max(3.0, num_rows * 0.8 + 1.5)
    fig, ax = plt.subplots(figsize=(16, fig_height))

    _draw_flame_bars(ax, rows, clock_khz)
    _style_flame_axes(
        ax, fig, num_rows, kernel_name, total, clock_khz,
    )

    plt.tight_layout()
    fig.savefig(output_path, format='svg')
    plt.close(fig)
    print(f"\nFlamegraph saved to {output_path}")


def _draw_flame_bars(ax, rows, clock_khz):
    """Draw labeled rectangles for each flame bar."""
    from matplotlib.patches import Rectangle

    bar_height = 0.7
    for bar in rows:
        name, row, x_start, width, color, cycles, pct = bar
        rect = Rectangle(
            (x_start, row), width, bar_height,
            facecolor=color, edgecolor='white',
            linewidth=1.5,
        )
        ax.add_patch(rect)

        # Truncate label for display
        short_name = name.split(":")[-1] if ":" in name else name
        label = f"{short_name}  {fmt_cycles(cycles)}  ({pct:.1f}%)"
        short = f"{short_name} ({pct:.1f}%)"
        display_label = label if width > 0.25 else short
        if width < 0.05:
            display_label = ""

        ax.text(
            x_start + width / 2, row + bar_height / 2,
            display_label,
            ha='center', va='center',
            fontsize=8 if width > 0.15 else 6,
            fontweight='bold', color='white',
            clip_on=True,
        )


def _style_flame_axes(ax, fig, num_rows, kernel_name,
                      total, clock_khz):
    """Apply dark-theme styling to flamegraph axes."""
    bar_height = 0.7
    ax.set_xlim(-0.02, 1.02)
    ax.set_ylim(-0.3, num_rows + 0.3)
    ax.set_xlabel("Fraction of total cycles", fontsize=11)
    ax.set_ylabel("Nesting depth", fontsize=11)
    ax.set_yticks(
        [i + bar_height / 2 for i in range(num_rows)]
    )
    ax.set_yticklabels(
        [f"depth {i}" for i in range(num_rows)]
    )
    ax.set_title(
        f"{kernel_name.upper()} Kernel Flamegraph "
        f"({fmt_cycles(total)} total cycles, "
        f"{fmt_time(cycles_to_time(total, clock_khz))})",
        fontsize=13, fontweight='bold',
    )
    bg = '#2c3e50'
    ax.set_facecolor(bg)
    fig.patch.set_facecolor(bg)
    ax.tick_params(colors='white')
    for attr in [ax.xaxis.label, ax.yaxis.label, ax.title]:
        attr.set_color('white')
    for spine in ax.spines.values():
        spine.set_color('white')
    for lbl in ax.get_yticklabels() + ax.get_xticklabels():
        lbl.set_color('white')


# ── Tree layout ────────────────────────────────────────


def _layout_tree(node, row, x_start, x_end, total_cycles):
    """Recursively lay out tree nodes as flat bar list.

    Each node occupies [x_start, x_end]. Children are placed
    left-to-right within that range, proportional to their
    cycle count relative to the sum of all siblings.

    Returns:
        Flat list of (name, row, x, w, color, cycles, pct).
    """
    width = x_end - x_start
    pct = (
        node["cycles"] / total_cycles * 100
        if total_cycles > 0 else 0
    )
    bars = [(
        node["name"], row, x_start, width,
        node["color"], node["cycles"], pct,
    )]

    children = node.get("children", [])
    if not children:
        return bars

    parent_cycles = node["cycles"]
    if parent_cycles <= 0:
        return bars

    # Size children relative to the PARENT's cycles.
    # Remaining width is overhead (uninstrumented code
    # between children). This makes the flamegraph show
    # gaps where init, bookkeeping, or loop overhead lives.
    cursor = x_start
    for child in children:
        child_frac = child["cycles"] / parent_cycles
        child_w = width * child_frac
        child_end = cursor + child_w
        bars.extend(
            _layout_tree(
                child, row + 1, cursor,
                child_end, total_cycles,
            )
        )
        cursor = child_end

    return bars


# ── Interactive HTML flamegraph ────────────────────────


def _jitter_color(name):
    """Generate a warm Gregg-style color from a bar name."""
    h = int(hashlib.md5(name.encode()).hexdigest(), 16)
    hue = (h % 60) / 360.0
    sat = 0.7 + (h >> 8 & 0xFF) / 850.0
    lit = 0.5 + (h >> 16 & 0xFF) / 1275.0
    r, g, b = colorsys.hls_to_rgb(hue, lit, sat)
    return f"rgb({int(r*255)},{int(g*255)},{int(b*255)})"


def _read_cu_source(kernel_name):
    """Read CUDA source file for the given kernel."""
    filename = f"cuda_{kernel_name}.cu"
    path = _PROJECT_ROOT / "GPU" / filename
    if not path.exists():
        print(f"WARNING: {path} not found, "
              "source panel will be empty.")
        return ""
    return path.read_text(encoding="utf-8")


def _highlight_cuda_source(source):
    """Apply regex-based syntax highlighting to CUDA source.

    Returns list of HTML-escaped, highlighted lines.
    """
    keywords = (
        r'\b(if|else|for|while|return|break|continue|'
        r'int|float|bool|void|const|char|signed|'
        r'unsigned|long|short|double|int8_t|'
        r'__global__|__device__|__shared__|'
        r'__syncthreads|__ldg|__expf|__int2float_rn|'
        r'__uint2float_rn|threadIdx|blockIdx|blockDim|'
        r'clock64)\b'
    )
    types_re = (
        r'\b(curandState|dim3|size_t)\b'
    )

    highlighted = []
    for line in source.splitlines():
        esc = (line
               .replace("&", "&amp;")
               .replace("<", "&lt;")
               .replace(">", "&gt;"))
        esc = re.sub(
            r'(//.*)',
            r'<span class="cm">\1</span>', esc,
        )
        esc = re.sub(
            r'^(\s*#\w+.*)',
            r'<span class="pp">\1</span>', esc,
        )
        esc = re.sub(
            r'(&quot;[^&]*&quot;|"[^"]*")',
            r'<span class="st">\1</span>', esc,
        )
        esc = re.sub(
            r'\b(\d+\.?\d*[fFL]?)\b',
            r'<span class="nu">\1</span>', esc,
        )
        esc = re.sub(
            keywords,
            r'<span class="kw">\1</span>', esc,
        )
        esc = re.sub(
            types_re,
            r'<span class="ty">\1</span>', esc,
        )
        highlighted.append(esc)
    return highlighted


def _compute_direct_lines(source_map):
    """Compute direct lines for each region.

    Direct lines = region's line range minus union of all
    child regions' ranges.
    """
    direct = {}
    for idx, (start, end) in source_map.items():
        own = set(range(start, end + 1))
        for other_idx, (cs, ce) in source_map.items():
            if other_idx == idx:
                continue
            if cs >= start and ce <= end and (
                cs > start or ce < end
            ):
                own -= set(range(cs, ce + 1))
        direct[idx] = sorted(own)
    return direct


def _build_source_html(highlighted_lines, source_map,
                       line_offset):
    """Build source code HTML with data-regions attributes."""
    line_regions = {}
    for idx, (start, end) in source_map.items():
        for ln in range(start, end + 1):
            line_regions.setdefault(ln, set()).add(idx)

    parts = []
    for i, html_line in enumerate(highlighted_lines):
        ln = line_offset + i
        regions = line_regions.get(ln, set())
        regions_attr = ",".join(
            str(r) for r in sorted(regions)
        )
        parts.append(
            f'<span class="src-line" '
            f'data-line="{ln}" '
            f'data-regions="{regions_attr}">'
            f'<span class="ln">{ln:4d}</span> '
            f'{html_line}</span>'
        )
    return "\n".join(parts)


def _derive_bar_hierarchy(bars):
    """Set parent/children on bars from row layout."""
    eps = 1e-9
    for bar_i in bars:
        for bar_j in bars:
            if bar_j["row"] != bar_i["row"] + 1:
                continue
            if (bar_j["x"] >= bar_i["x"] - eps
                    and bar_j["x"] + bar_j["w"]
                    <= bar_i["x"] + bar_i["w"] + eps):
                bar_j["parent"] = bar_i["name"]
                bar_i["children"].append(bar_j["name"])


def _build_profile_json(data, clock_khz, kernel_name,
                        manifest, num_sweeps, gpu_name):
    """Build JSON profile data for the HTML template."""
    active = data[data.any(axis=1)]
    assert len(active) > 0, (
        "No active work units — cannot build profile"
    )

    avg = active.mean(axis=0)
    source_map = _source_map_from_manifest(manifest)
    region_names = _region_names_from_manifest(manifest)
    direct_lines = _compute_direct_lines(source_map)

    tree = _build_tree_from_manifest(manifest, avg)
    total = tree["cycles"]
    rows = _layout_tree(tree, 0, 0.0, 1.0, total)

    bars = []
    for bar in rows:
        name, row, x_start, width, color, cycles, pct = bar
        # Find matching region by label
        region_idx = None
        src_lines = None
        direct = None
        for r in manifest["regions"]:
            if r["label"] == name:
                region_idx = r["id"]
                break
        if region_idx is not None and region_idx in source_map:
            s, e = source_map[region_idx]
            src_lines = [s, e]
            direct = direct_lines.get(region_idx, [])
        bars.append({
            "name": name,
            "fullName": name,
            "row": row,
            "x": x_start,
            "w": width,
            "color": _jitter_color(name),
            "cycles": int(cycles),
            "pct": round(pct, 2),
            "time": fmt_time(
                cycles_to_time(cycles, clock_khz)
            ),
            "sourceLines": src_lines,
            "directLines": direct,
            "parent": None,
            "children": [],
        })

    _derive_bar_hierarchy(bars)
    topo = get_topology_stats()

    return {
        "kernel": kernel_name,
        "gpu": gpu_name,
        "clockMhz": round(clock_khz / 1000.0),
        "totalCycles": int(total),
        "totalTime": fmt_time(
            cycles_to_time(total, clock_khz)
        ),
        "numSweeps": num_sweeps,
        "bars": bars,
        "topology": {
            "nodes": topo[0],
            "edges": topo[1],
            "avgDegree": round(topo[2], 1),
            "nodesPerColor": topo[3],
            "numColors": topo[4],
        },
    }


def _render_flame_svg(bars, viewbox_w=1200,
                      bar_height=18, pad=1):
    """Build inline SVG with viewBox, <g> groups, clipPath."""
    max_row = max(b["row"] for b in bars)
    svg_h = (max_row + 1) * (bar_height + pad) + pad

    parts = [
        f'<svg id="flame-svg" width="100%" '
        f'height="{svg_h}" '
        f'viewBox="0 0 {viewbox_w} {svg_h}" '
        f'preserveAspectRatio="none" '
        f'xmlns="http://www.w3.org/2000/svg">',
        '<defs>',
    ]

    for idx, b in enumerate(bars):
        x = b["x"] * viewbox_w
        w = b["w"] * viewbox_w
        y = ((max_row - b["row"])
             * (bar_height + pad) + pad)
        parts.append(
            f'<clipPath id="cp-{idx}">'
            f'<rect x="{x:.2f}" y="{y}" '
            f'width="{max(w, 0.5):.2f}" '
            f'height="{bar_height}"/>'
            f'</clipPath>'
        )
    parts.append('</defs>')

    for idx, b in enumerate(bars):
        x = b["x"] * viewbox_w
        w = b["w"] * viewbox_w
        y = ((max_row - b["row"])
             * (bar_height + pad) + pad)
        src = (json.dumps(b["sourceLines"])
               if b["sourceLines"] else "null")
        direct = (json.dumps(b["directLines"])
                  if b["directLines"] else "null")

        parts.append(
            f'<g class="flame-bar" '
            f'data-idx="{idx}" '
            f'data-name="{b["name"]}" '
            f'data-full-name="{b["fullName"]}" '
            f'data-cycles="{b["cycles"]}" '
            f'data-pct="{b["pct"]}" '
            f'data-time="{b["time"]}" '
            f"data-source-lines='{src}' "
            f"data-direct-lines='{direct}'>"
        )
        parts.append(
            f'<rect x="{x:.2f}" y="{y}" '
            f'width="{max(w, 0.5):.2f}" '
            f'height="{bar_height}" '
            f'fill="{b["color"]}"/>'
        )
        # Short label for SVG
        label = b["name"].split(":")[-1] if ":" in b["name"] else b["name"]
        parts.append(
            f'<text clip-path="url(#cp-{idx})" '
            f'x="{x + 3:.2f}" '
            f'y="{y + bar_height - 4}" '
            f'font-size="12" fill="#000" '
            f'font-family="monospace" '
            f'pointer-events="none">'
            f'{label}</text>'
        )
        parts.append('</g>')

    parts.append('</svg>')
    return "\n".join(parts)


def _build_metrics_html(data, clock_khz, manifest,
                        num_sweeps, gpu_name, topo):
    """Build metrics table HTML for the collapsible panel."""
    active = data[data.any(axis=1)]
    avg = active.mean(axis=0)
    total = sum(
        avg[r["id"]]
        for r in manifest["regions"]
        if r["parent_id"] is None
    )

    rows = []
    for r in sorted(manifest["regions"],
                    key=lambda r: r["id"]):
        rid = r["id"]
        if rid >= len(avg):
            continue
        c = avg[rid]
        t = cycles_to_time(c, clock_khz)
        pct = (c / total * 100) if total > 0 else 0
        name = r["label"]
        rows.append(
            f'<tr><td>{name}</td>'
            f'<td class="r">{fmt_cycles(c)}</td>'
            f'<td class="r">{fmt_time(t)}</td>'
            f'<td class="r">{pct:.1f}%</td></tr>'
        )

    topo_html = (
        f'<p class="topo">Topology: {topo["nodes"]} nodes, '
        f'{topo["edges"]} edges, '
        f'avg degree {topo["avgDegree"]}, '
        f'{topo["numColors"]} colors, '
        f'~{topo["nodesPerColor"]} nodes/color</p>'
    )

    return (
        f'{topo_html}'
        f'<table class="metrics">'
        f'<tr><th>Region</th><th>Avg Cycles</th>'
        f'<th>Time</th><th>%</th></tr>'
        f'{"".join(rows)}'
        f'</table>'
    )


# Self-contained HTML template with CSS + JS.
HTML_TEMPLATE = '''\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title><!--KERNEL_NAME--> Kernel Flamegraph</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{background:#1a1a2e;color:#e0e0e0;
font-family:'Fira Code','Consolas',monospace;
font-size:13px}
.header{background:#16213e;padding:12px 20px;
border-bottom:1px solid #0f3460;
font-size:16px;font-weight:bold;color:#e94560}
.header span{color:#888;font-size:13px;
font-weight:normal;margin-left:12px}
.toolbar{display:flex;align-items:center;gap:8px;
padding:6px 20px;background:#16213e;
border-bottom:1px solid #0f3460;height:30px}
.toolbar button{background:#0f3460;color:#e0e0e0;
border:1px solid #e94560;border-radius:4px;
padding:2px 10px;cursor:pointer;font-size:12px;
font-family:inherit}
.toolbar button:disabled{opacity:0.4;cursor:default}
.toolbar button:not(:disabled):hover{
background:#e94560;color:#fff}
.toolbar input{background:#0f0f23;color:#e0e0e0;
border:1px solid #333;border-radius:4px;
padding:2px 8px;font-size:12px;font-family:inherit;
width:200px}
.toolbar input:focus{outline:none;
border-color:#e94560}
#search-match{color:#888;font-size:12px}
.container{display:flex;flex-direction:column;
height:calc(100vh - 140px)}
.flame-panel{flex:1 1 auto;padding:16px;
overflow:auto;border-bottom:1px solid #0f3460;
position:relative;min-height:200px}
.resize-handle{flex:0 0 6px;background:#0f3460;
cursor:row-resize;display:flex;align-items:center;
justify-content:center}
.resize-handle:hover,.resize-handle.active{
background:#e94560}
.resize-handle::after{content:'';width:40px;
height:2px;background:#888;border-radius:1px}
.source-panel{flex:0 0 280px;padding:16px;
overflow:auto;background:#0f0f23}
.source-panel pre{line-height:1.6;white-space:pre;
tab-size:4}
.src-line{display:block;padding:0 8px;
border-left:3px solid transparent;
transition:background .15s,border-color .15s}
.src-line:hover{background:#1a1a4e}
.src-line.hl{background:#2a2a5e;
border-left-color:#e94560}
.src-line.hl-direct{background:#3a2a3e;
border-left-color:#ff6b9d}
.ln{color:#555;user-select:none;
display:inline-block;width:4ch;text-align:right;
margin-right:8px}
.kw{color:#c678dd} .ty{color:#e5c07b}
.cm{color:#5c6370;font-style:italic}
.pp{color:#d19a66} .st{color:#98c379}
.nu{color:#d19a66}
.flame-bar{cursor:pointer}
.flame-bar rect{stroke:none;
transition:opacity .15s}
.flame-bar:hover rect{stroke:#000;
stroke-width:0.5}
.flame-bar.selected rect{stroke:#e94560;
stroke-width:2}
.flame-bar.matched rect{fill:#ee0 !important}
.flame-bar.dimmed rect{opacity:0.3}
#info-bar{height:18px;background:#16213e;
padding:0 12px;font-size:12px;color:#e0e0e0;
font-family:monospace;line-height:18px;
border-top:1px solid #0f3460;overflow:hidden;
white-space:nowrap}
.metrics-panel{border-top:1px solid #0f3460;
padding:12px 20px;background:#16213e}
.metrics-panel summary{cursor:pointer;
color:#e94560;font-weight:bold;font-size:14px;
user-select:none}
.metrics-panel summary:hover{color:#ff6b9d}
.metrics{width:100%;border-collapse:collapse;
margin-top:8px;font-size:12px}
.metrics th{text-align:left;color:#888;
border-bottom:1px solid #333;padding:4px 12px}
.metrics td{padding:4px 12px;
border-bottom:1px solid #222}
.metrics .r{text-align:right;font-variant-numeric:
tabular-nums}
.topo{color:#888;margin-bottom:8px;font-size:12px}
</style>
</head>
<body>
<div class="header"><!--KERNEL_NAME--> Kernel Profile
<span><!--GPU_INFO--></span></div>
<div class="toolbar">
<button id="reset-zoom" disabled>Reset Zoom</button>
<input id="search-input" type="text"
 placeholder="Search regex...">
<span id="search-match"></span>
</div>
<div class="container">
<div class="flame-panel">
<!--FLAME_SVG-->
</div>
<div class="resize-handle" id="resize-handle"></div>
<div class="source-panel" id="source-panel">
<pre><!--SOURCE_HTML--></pre>
</div>
</div>
<div id="info-bar">&nbsp;</div>
<div class="metrics-panel">
<details>
<summary>Metrics &amp; Topology</summary>
<!--METRICS_HTML-->
</details>
</div>
<script>
(function() {
"use strict";
var profile = <!--PROFILE_JSON-->;
var svg = document.getElementById("flame-svg");
var barEls = document.querySelectorAll(".flame-bar");
var srcLines = document.querySelectorAll(".src-line");
var infoBar = document.getElementById("info-bar");
var resetBtn = document.getElementById("reset-zoom");
var searchInput = document.getElementById("search-input");
var searchMatch = document.getElementById("search-match");

var origViewBox = svg.getAttribute("viewBox");
var zoomStack = [];
var selectedBar = null;

function clearSourceHL() {
  for (var j = 0; j < srcLines.length; j++)
    srcLines[j].classList.remove("hl","hl-direct");
}

function clearBarSelection() {
  for (var i = 0; i < barEls.length; i++)
    barEls[i].classList.remove("selected");
  selectedBar = null;
}

function highlightSourceRange(start, end) {
  for (var i = 0; i < srcLines.length; i++) {
    var ln = parseInt(srcLines[i].dataset.line, 10);
    if (ln >= start && ln <= end)
      srcLines[i].classList.add("hl");
  }
  var first = document.querySelector(".src-line.hl");
  if (first) first.scrollIntoView(
    {behavior:"smooth",block:"center"});
}

function highlightDirectLines(lines) {
  for (var i = 0; i < srcLines.length; i++) {
    var ln = parseInt(srcLines[i].dataset.line, 10);
    if (lines.indexOf(ln) !== -1)
      srcLines[i].classList.add("hl-direct");
  }
  var first = document.querySelector(
    ".src-line.hl-direct");
  if (first) first.scrollIntoView(
    {behavior:"smooth",block:"center"});
}

function highlightBarsForRegions(regionStr) {
  if (!regionStr) return;
  var regions = regionStr.split(",").map(Number);
  for (var i = 0; i < barEls.length; i++) {
    var bd = profile.bars[i];
    if (!bd) continue;
    for (var r = 0; r < regions.length; r++) {
      var ri = regions[r];
      if (bd.sourceLines) {
        var sm = bd.sourceLines;
        // Check if this bar's source range contains
        // any of the matching region ranges
        barEls[i].classList.add("selected");
      }
    }
  }
}

function setInfo(text) {
  infoBar.textContent = text || "\u00a0";
}

/* Zoom */

function zoomToBar(barData) {
  var vbW = 1200;
  var x = barData.x * vbW;
  var w = barData.w * vbW;
  var vb = svg.getAttribute("viewBox").split(" ");
  zoomStack.push(vb.join(" "));
  svg.setAttribute("viewBox",
    x + " 0 " + w + " " + vb[3]);
  resetBtn.disabled = false;
  setInfo("Zoomed: " + barData.name +
    " (" + barData.pct + "%, " + barData.time + ")");
}

function resetZoom() {
  svg.setAttribute("viewBox", origViewBox);
  zoomStack = [];
  resetBtn.disabled = true;
  setInfo("");
}

resetBtn.addEventListener("click", function() {
  resetZoom();
});

/* Search */

searchInput.addEventListener("input", function() {
  var q = this.value.trim();
  if (!q) {
    for (var i = 0; i < barEls.length; i++) {
      barEls[i].classList.remove("matched","dimmed");
    }
    searchMatch.textContent = "";
    setInfo("");
    return;
  }
  var re;
  try { re = new RegExp(q, "i"); }
  catch(e) { return; }
  var matched = 0;
  for (var i = 0; i < barEls.length; i++) {
    var name = barEls[i].dataset.name;
    if (re.test(name)) {
      barEls[i].classList.add("matched");
      barEls[i].classList.remove("dimmed");
      matched++;
    } else {
      barEls[i].classList.remove("matched");
      barEls[i].classList.add("dimmed");
    }
  }
  var msg = matched + " of " + barEls.length +
    " bars match";
  searchMatch.textContent = msg;
  setInfo(msg);
});

/* Hover */

for (var i = 0; i < barEls.length; i++) {
  (function(bar, idx) {
    bar.addEventListener("mouseenter", function() {
      var bd = profile.bars[idx];
      if (!bd) return;
      setInfo(bd.name + "  |  " +
        parseInt(bd.cycles,10).toLocaleString() +
        " cycles  |  " + bd.time +
        "  |  " + bd.pct + "%");
      if (!selectedBar) {
        clearSourceHL();
        var src = JSON.parse(
          this.getAttribute("data-source-lines"));
        if (src) highlightSourceRange(src[0], src[1]);
      }
    });
    bar.addEventListener("mouseleave", function() {
      setInfo("");
      if (!selectedBar) clearSourceHL();
    });
    bar.addEventListener("click", function(e) {
      e.stopPropagation();
      var bd = profile.bars[idx];
      if (!bd) return;
      clearBarSelection();
      clearSourceHL();
      zoomToBar(bd);
      selectedBar = this;
      this.classList.add("selected");
      var direct = JSON.parse(
        this.getAttribute("data-direct-lines"));
      if (direct && direct.length > 0) {
        highlightDirectLines(direct);
      } else {
        var src = JSON.parse(
          this.getAttribute("data-source-lines"));
        if (src) highlightSourceRange(src[0], src[1]);
      }
    });
  })(barEls[i], parseInt(barEls[i].dataset.idx, 10));
}

/* Source line click */

for (var j = 0; j < srcLines.length; j++) {
  (function(line) {
    line.addEventListener("click", function() {
      clearBarSelection();
      clearSourceHL();
      this.classList.add("hl");
      highlightBarsForRegions(this.dataset.regions);
    });
  })(srcLines[j]);
}

/* Click background to deselect */

document.querySelector(".flame-panel")
  .addEventListener("click", function(e) {
    if (e.target.closest(".flame-bar")) return;
    clearBarSelection();
    clearSourceHL();
  });

/* Resize handle: drag to resize source panel */

(function() {
  var handle = document.getElementById("resize-handle");
  var panel = document.getElementById("source-panel");
  var container = document.querySelector(".container");
  var dragging = false;

  handle.addEventListener("mousedown", function(e) {
    e.preventDefault();
    dragging = true;
    handle.classList.add("active");
    document.body.style.cursor = "row-resize";
    document.body.style.userSelect = "none";
  });

  document.addEventListener("mousemove", function(e) {
    if (!dragging) return;
    var containerRect = container.getBoundingClientRect();
    var newH = containerRect.bottom - e.clientY - 6;
    if (newH < 60) newH = 60;
    if (newH > containerRect.height - 100) {
      newH = containerRect.height - 100;
    }
    panel.style.flexBasis = newH + "px";
  });

  document.addEventListener("mouseup", function() {
    if (!dragging) return;
    dragging = false;
    handle.classList.remove("active");
    document.body.style.cursor = "";
    document.body.style.userSelect = "";
  });
})();

})();
</script>
</body>
</html>
'''


def generate_flamegraph_html(data, clock_khz, kernel_name,
                             manifest, num_sweeps, gpu_name,
                             output_path):
    """Generate interactive HTML flamegraph with source linking.

    Args:
        data: Raw profiling array (work_units x regions).
        clock_khz: GPU clock rate in kHz.
        kernel_name: 'gibbs' or 'sa'.
        manifest: Profiling manifest dict.
        num_sweeps: Number of sweeps used in profiling.
        gpu_name: GPU device name string.
        output_path: Output HTML file path.
    """
    source_map = _source_map_from_manifest(manifest)

    # Determine source line range to extract
    all_starts = [s for s, _ in source_map.values()]
    all_ends = [e for _, e in source_map.values()]
    line_start = min(all_starts) - 5
    line_end = max(all_ends) + 5

    # Read and extract source
    full_source = _read_cu_source(kernel_name)
    if full_source:
        all_lines = full_source.splitlines()
        extract = all_lines[line_start - 1:line_end]
    else:
        extract = ["// Source file not found"]
        line_start = 1

    highlighted = _highlight_cuda_source("\n".join(extract))
    source_html = _build_source_html(
        highlighted, source_map, line_start,
    )

    profile = _build_profile_json(
        data, clock_khz, kernel_name, manifest,
        num_sweeps, gpu_name,
    )
    flame_svg = _render_flame_svg(profile["bars"])
    metrics_html = _build_metrics_html(
        data, clock_khz, manifest, num_sweeps,
        gpu_name, profile["topology"],
    )

    clock_mhz = clock_khz / 1000.0
    gpu_info = f"{gpu_name} @ {clock_mhz:.0f} MHz"

    html = (HTML_TEMPLATE
            .replace('<!--PROFILE_JSON-->',
                     json.dumps(profile))
            .replace('<!--SOURCE_HTML-->', source_html)
            .replace('<!--FLAME_SVG-->', flame_svg)
            .replace('<!--KERNEL_NAME-->',
                     kernel_name.upper())
            .replace('<!--GPU_INFO-->', gpu_info)
            .replace('<!--METRICS_HTML-->', metrics_html))

    Path(output_path).write_text(html, encoding="utf-8")
    print(f"\nInteractive flamegraph saved to {output_path}")


# ── Matplotlib plot (legacy) ───────────────────────────


def plot_profile(data, manifest, clock_khz, kernel_name,
                 output_path):
    """Generate profile visualization plots."""
    try:
        import matplotlib
        matplotlib.use('Agg')
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib not available, skipping plots.")
        return

    active = data[data.any(axis=1)]
    if len(active) == 0:
        return

    avg = active.mean(axis=0)

    # Pick top-level regions for pie chart
    top_regions = [
        r for r in manifest["regions"]
        if r["depth"] == 1
    ]
    if not top_regions:
        top_regions = [
            r for r in manifest["regions"]
            if r["parent_id"] is None
        ]

    labels = []
    sizes = []
    for r in top_regions[:8]:
        short = r["label"].split(":")[-1]
        labels.append(short)
        sizes.append(max(0, float(avg[r["id"]])))

    nonzero = [
        (l, s) for l, s in zip(labels, sizes) if s > 0
    ]
    if not nonzero:
        return
    labels, sizes = zip(*nonzero)

    fig, axes = plt.subplots(1, 2, figsize=(14, 6))

    axes[0].pie(sizes, labels=labels, autopct='%1.1f%%')
    axes[0].set_title(
        f"{kernel_name.upper()} Top-Level Breakdown"
    )

    totals = active[:, 0]
    times_ms = totals / (clock_khz * 1.0)
    axes[1].hist(times_ms, bins=min(50, len(active)),
                 edgecolor='black', alpha=0.7)
    axes[1].set_xlabel("Total time (ms)")
    axes[1].set_ylabel("Count")
    axes[1].set_title(
        f"{kernel_name.upper()} Total Time Distribution"
    )

    plt.tight_layout()
    plt.savefig(output_path, dpi=150)
    print(f"\nPlot saved to {output_path}")


# ── Main ───────────────────────────────────────────────


def main():
    parser = argparse.ArgumentParser(
        description="CUDA kernel region profiling"
    )
    parser.add_argument(
        "--kernel", choices=["gibbs", "sa"],
        default="gibbs",
        help="Which kernel to profile (default: gibbs)",
    )
    parser.add_argument(
        "--sweeps", type=int, default=1000,
        help="Number of sweeps (default: 1000)",
    )
    parser.add_argument(
        "--reads", type=int, default=100,
        help="Number of reads (default: 100)",
    )
    parser.add_argument(
        "--plot", action="store_true",
        help="Generate matplotlib visualization",
    )
    parser.add_argument(
        "--flame", action="store_true",
        help="Generate flamegraph SVG visualization",
    )
    parser.add_argument(
        "--flame-html", action="store_true",
        help="Generate interactive HTML flamegraph "
             "with source linking",
    )
    parser.add_argument(
        "--output", type=str, default=None,
        help="Output path for --flame-html "
             "(default: flamegraphs/flamegraph_KERNEL.html)",
    )
    args = parser.parse_args()

    gpu_name, clock_khz, clock_mhz = get_gpu_info()
    print(f"GPU: {gpu_name}, SM clock: {clock_mhz:.0f} MHz")
    print(f"Kernel: {args.kernel}, sweeps={args.sweeps}, "
          f"reads={args.reads}")

    if args.flame or args.flame_html:
        os.makedirs("flamegraphs", exist_ok=True)

    kernel = args.kernel

    # Collect profile data (auto-instruments on the fly)
    if kernel == "gibbs":
        data = profile_gibbs(args.reads, args.sweeps)
    else:
        data = profile_sa(args.reads, args.sweeps)

    # Load manifest (generated during profiling)
    manifest = _load_manifest(kernel)

    # Print text profile
    print_profile(data, clock_khz, manifest,
                  args.reads, args.sweeps)

    # Generate outputs
    if args.plot:
        plot_profile(
            data, manifest, clock_khz,
            kernel, f"profile_{kernel}.png",
        )
    if args.flame:
        generate_flamegraph(
            data, clock_khz, kernel, manifest,
            f"flamegraphs/flamegraph_{kernel}.svg",
        )
    if args.flame_html:
        out = (args.output
               or f"flamegraphs/flamegraph_{kernel}.html")
        generate_flamegraph_html(
            data, clock_khz, kernel, manifest,
            args.sweeps, gpu_name, out,
        )


if __name__ == "__main__":
    main()
